name = "workers-tunnel"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-02"

[build]
command = "cargo install -q worker-build && worker-build --release"

[observability]
enabled = true
head_sampling_rate = 1

[vars]
USER_ID = "9a6e3c94-3bbc-4cc6-accb-acdd7e202fba"
PROXY_IP = "gh.proxy.farelra.my.id"
FALLBACK_SITE = "https://ifconfig.me"
